---
displayName: Apache Camel K
description: Stack with environment ready to develop Integration projects with Apache Camel K
tags: ["Apache Camel K", "Red Hat Fuse", "Integration"]
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
globalMemoryLimit: 2930Mi
